use_frameworks!

target 'ACRAutoComplete_Example' do
  pod 'ACRAutoComplete', :path => '../'

end

target 'ACRAutoComplete_Tests' do
#    inherit! :search_paths

  pod 'ACRAutoComplete', :path => '../'
end
