# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode8.2
xcode_workspace: Example/ACRAutoComplete.xcworkspace
xcode_scheme: ACRAutoComplete-Example
xcode_sdk: iphonesimulator10.1
language: objective-c
cache: cocoapods
podfile: Example/Podfile
before_install:
- gem install cocoapods # Since Travis is not always on latest version
- pod install --project-directory=Example
# script:
# - set -o pipefail && xcodebuild test -workspace Example/ACRAutoComplete.xcworkspace -scheme ACRAutoComplete-Example -sdk iphonesimulator10.1 -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.1,id=E35A39A9-0197-4428-A846-D75DDE6F0E98' ONLY_ACTIVE_ARCH=NO | xcpretty
# - pod lib lint
