# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode8
xcode_workspace: Example/ACRAutoComplete.xcworkspace
xcode_scheme: ACRAutoComplete-Example
xcode_sdk: iphonesimulator10.1
language: objective-c
cache: cocoapods
podfile: Example/Podfile
before_install:
- gem install cocoapods # Since Travis is not always on latest version
- pod install --project-directory=Example

script:
- set -o pipefail && xcodebuild clean build test -workspace Example/ACRAutoComplete.xcworkspace -scheme ACRAutoComplete-Example -destination "platform=iOS Simulator,name=iPhone 7" ONLY_ACTIVE_ARCH=NO
- pod lib lint
after_success:
- bash <(curl -s https://codecov.io/bash)
